language: php
cache:
  directories:
    - ~/.npm
    - node_modules/
    - vendor/
notifications:
  email: false
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y nodejs
before_script:
  - composer install
script:
  - echo 'Done.'
after_success:
  - npm install
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
